DINO_DB_HOST: "localhost"
DINO_DB_NAME: "dino"
DINO_DB_USER: "dinouser"
DINO_DB_PASS: "dinopass"
DINO_EXT_QUEUE_HOST: "redis://localhost:6379"
DINO_EXT_QUEUE_USER: ""
DINO_EXT_QUEUE_PASS: ""
DINO_QUEUE_HOST: "localhost"
DINO_QUEUE_USER: "dino"
DINO_QUEUE_PASS: "dino"
DINO_QUEUE_VHOST: "/dino"
DINO_COORDINATOR_HOST: "localhost:6379"
DINO_NUTCRACKER_AUTH_HOSTS: "localhost:6379:9"
DINO_NUTCRACKER_CACHE_HOSTS: "localhost:6379:8,localhost:6380:8"
DINO_AUTH_HOST: "localhost:63790"
DINO_CACHE_HOST: "localhost:63790"
DINO_CASSANDRA_HOST_1: "localhost"
DINO_CASSANDRA_HOST_2: "localhost"
DINO_EXT_QUEUE_VHOST: "/"
DINO_STATSD_HOST: "localhost"
DINO_REQ_LOG_LOC: ""
DINO_WEB_AUTH_INSECURE: "True"
DINO_WEB_AUTH_BASE: ""
DINO_WEB_AUTH_PATH: ""
DINO_WEB_AUTH_SERVICE_ID: ""
DINO_WEB_AUTH_SERVICE_SECRET: ""
DINO_WEB_AUTH_URL: ""
DINO_WEB_AUTH_TOKEN_URL: ""
DINO_WEB_AUTH_CALLBACK_URL: ""
DINO_WEB_AUTH_UNAUTH_URL: ""
DINO_WEB_USE_FLOATING_MENU: "False"
DINO_REMOTE_HOST: "http://127.0.0.1:8080"
DINO_PATH_CAN_WHISPER: "v1/whisper"
DINO_REMOTE_PRIVATE_KEY: "some-key"
