DINO_REQ_LOG_LOC: ""
FLASK_SECRET: ""
DINO_AUTH_HOST: "redisdino:6379"
DINO_CACHE_HOST: "redisdino:6379"
DINO_COORDINATOR_HOST: "redisdino:6379"

DINO_DB_HOST: "mysql"
DINO_DB_NAME: "dino"
DINO_DB_USER: "root"
DINO_DB_PASS: "root"

DINO_QUEUE_HOST: "rabbitmq"
DINO_QUEUE_USER: "dino"
DINO_QUEUE_PASS: "dino"
DINO_QUEUE_VHOST: "/dino"

DINO_REMOTE_HOST: "http://127.0.0.1:8080"
DINO_PATH_CAN_WHISPER: "v1/whisper"
DINO_REMOTE_PRIVATE_KEY: "some-key"

DINO_EXT_QUEUE_HOST_1: kafka-1
DINO_EXT_QUEUE_HOST_1: kafka-2
DINO_EXT_QUEUE_NAME: "dino"
DINO_EXT_STATUS_QUEUE: "dino_status"

DINO_CASSANDRA_HOST_1: "cass1"
DINO_CASSANDRA_HOST_2: "cass2"
